# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VariableList")

model_instance <- VariableList$new()

test_that("metadata", {
  # tests for the property `metadata` (Metadata)

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("pagination", {
  # tests for the property `pagination` (Pagination)

  # uncomment below to test the property
  #expect_equal(model.instance$`pagination`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (array[Variable])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
