# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject3")

model_instance <- InlineObject3$new()

test_that("metadata", {
  # tests for the property `metadata` (Metadata)

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})
