# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Metadata")

model_instance <- Metadata$new()

test_that("status", {
  # tests for the property `status` (character)
  # HTTP status of the response (e.g., OK or ERROR)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (character)
  # HTTP method of the request

  # uncomment below to test the property
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (character)
  # Requested URI path

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # Timestamp when response was generated

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (ComponentsSchemasMetadataError)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})
