=begin
#Mednet EDC API

#The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

The version of the OpenAPI document: 1.0.15

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Visit
    # Unique study key
    attr_accessor :study_key

    # Unique system identifier for the subject visit instance
    attr_accessor :visit_id

    # Unique system identifier of the interval definition for this visit
    attr_accessor :interval_id

    # Name of the interval (visit) for this visit instance
    attr_accessor :interval_name

    # Mednet subject ID of the subject
    attr_accessor :subject_id

    # Protocol-assigned subject identifier
    attr_accessor :subject_key

    # Start date of the visit window (in YYYY-MM-DD format)
    attr_accessor :start_date

    # End date of the visit window (in YYYY-MM-DD format)
    attr_accessor :end_date

    # Due date of the visit (in YYYY-MM-DD format), if applicable
    attr_accessor :due_date

    # Actual date the visit took place (in YYYY-MM-DD format)
    attr_accessor :visit_date

    # Name of the form used to capture the actual visit date
    attr_accessor :visit_date_form

    # Variable name of the field capturing the actual visit date
    attr_accessor :visit_date_question

    # Whether the visit instance is marked as deleted
    attr_accessor :deleted

    # Date when this visit record was created
    attr_accessor :date_created

    # Date when this visit record was last modified
    attr_accessor :date_modified

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'study_key' => :'studyKey',
        :'visit_id' => :'visitId',
        :'interval_id' => :'intervalId',
        :'interval_name' => :'intervalName',
        :'subject_id' => :'subjectId',
        :'subject_key' => :'subjectKey',
        :'start_date' => :'startDate',
        :'end_date' => :'endDate',
        :'due_date' => :'dueDate',
        :'visit_date' => :'visitDate',
        :'visit_date_form' => :'visitDateForm',
        :'visit_date_question' => :'visitDateQuestion',
        :'deleted' => :'deleted',
        :'date_created' => :'dateCreated',
        :'date_modified' => :'dateModified'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'study_key' => :'String',
        :'visit_id' => :'Integer',
        :'interval_id' => :'Integer',
        :'interval_name' => :'String',
        :'subject_id' => :'Integer',
        :'subject_key' => :'String',
        :'start_date' => :'String',
        :'end_date' => :'String',
        :'due_date' => :'String',
        :'visit_date' => :'String',
        :'visit_date_form' => :'String',
        :'visit_date_question' => :'String',
        :'deleted' => :'Boolean',
        :'date_created' => :'String',
        :'date_modified' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Visit` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Visit`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'study_key')
        self.study_key = attributes[:'study_key']
      end

      if attributes.key?(:'visit_id')
        self.visit_id = attributes[:'visit_id']
      end

      if attributes.key?(:'interval_id')
        self.interval_id = attributes[:'interval_id']
      end

      if attributes.key?(:'interval_name')
        self.interval_name = attributes[:'interval_name']
      end

      if attributes.key?(:'subject_id')
        self.subject_id = attributes[:'subject_id']
      end

      if attributes.key?(:'subject_key')
        self.subject_key = attributes[:'subject_key']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      end

      if attributes.key?(:'visit_date')
        self.visit_date = attributes[:'visit_date']
      end

      if attributes.key?(:'visit_date_form')
        self.visit_date_form = attributes[:'visit_date_form']
      end

      if attributes.key?(:'visit_date_question')
        self.visit_date_question = attributes[:'visit_date_question']
      end

      if attributes.key?(:'deleted')
        self.deleted = attributes[:'deleted']
      end

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'date_modified')
        self.date_modified = attributes[:'date_modified']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          study_key == o.study_key &&
          visit_id == o.visit_id &&
          interval_id == o.interval_id &&
          interval_name == o.interval_name &&
          subject_id == o.subject_id &&
          subject_key == o.subject_key &&
          start_date == o.start_date &&
          end_date == o.end_date &&
          due_date == o.due_date &&
          visit_date == o.visit_date &&
          visit_date_form == o.visit_date_form &&
          visit_date_question == o.visit_date_question &&
          deleted == o.deleted &&
          date_created == o.date_created &&
          date_modified == o.date_modified
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [study_key, visit_id, interval_id, interval_name, subject_id, subject_key, start_date, end_date, due_date, visit_date, visit_date_form, visit_date_question, deleted, date_created, date_modified].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
