# coding: utf-8

"""
    Mednet EDC API

    The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

    The version of the OpenAPI document: 1.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.visits_api import VisitsApi


class TestVisitsApi(unittest.TestCase):
    """VisitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VisitsApi()

    def tearDown(self) -> None:
        pass

    def test_list_visits(self) -> None:
        """Test case for list_visits

        List visits (subject visit instances) in a study
        """
        pass


if __name__ == '__main__':
    unittest.main()
