# coding: utf-8

"""
    Mednet EDC API

    The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

    The version of the OpenAPI document: 1.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.administration_api import AdministrationApi


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdministrationApi()

    def tearDown(self) -> None:
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        List users and their roles in a study
        """
        pass


if __name__ == '__main__':
    unittest.main()
