# coding: utf-8

"""
    Mednet EDC API

    The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

    The version of the OpenAPI document: 1.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.keyword import Keyword

class TestKeyword(unittest.TestCase):
    """Keyword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Keyword:
        """Test Keyword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Keyword`
        """
        model = Keyword()
        if include_optional:
            return Keyword(
                keyword_name = '',
                keyword_key = '',
                keyword_id = 56,
                date_added = ''
            )
        else:
            return Keyword(
        )
        """

    def testKeyword(self):
        """Test Keyword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
