/*
Mednet EDC API

Testing RecordsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_RecordsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RecordsAPIService CreateRecords", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var studyKey string

		resp, httpRes, err := apiClient.RecordsAPI.CreateRecords(context.Background(), studyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordsAPIService ListRecords", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var studyKey string

		resp, httpRes, err := apiClient.RecordsAPI.ListRecords(context.Background(), studyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
