/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject5 from '../model/InlineObject5';
import UserList from '../model/UserList';

/**
* Administration service.
* @module api/AdministrationApi
* @version 1.0.15
*/
export default class AdministrationApi {

    /**
    * Constructs a new AdministrationApi. 
    * @alias module:api/AdministrationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the listUsers operation.
     * @callback module:api/AdministrationApi~listUsersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List users and their roles in a study
     * @param {String} studyKey Study key identifying the study context for the request
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page index to retrieve (0-based)
     * @param {Number} [size = 25)] Number of items to return per page (max 500)
     * @param {String} [sort] Sorting criteria in the format `property,ASC` or `property,DESC`. Can be repeated.
     * @param {Boolean} [includeInactive = false)] For user listing, whether to include inactive users
     * @param {module:api/AdministrationApi~listUsersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserList}
     */
    listUsers(studyKey, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'studyKey' is set
      if (studyKey === undefined || studyKey === null) {
        throw new Error("Missing the required parameter 'studyKey' when calling listUsers");
      }

      let pathParams = {
        'studyKey': studyKey
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort'],
        'includeInactive': opts['includeInactive']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKeyAuth', 'securityKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserList;
      return this.apiClient.callApi(
        '/studies/{studyKey}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
