/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComponentsSchemasIntervalFormsItem model module.
 * @module model/ComponentsSchemasIntervalFormsItem
 * @version 1.0.15
 */
class ComponentsSchemasIntervalFormsItem {
    /**
     * Constructs a new <code>ComponentsSchemasIntervalFormsItem</code>.
     * @alias module:model/ComponentsSchemasIntervalFormsItem
     */
    constructor() { 
        
        ComponentsSchemasIntervalFormsItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComponentsSchemasIntervalFormsItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComponentsSchemasIntervalFormsItem} obj Optional instance to populate.
     * @return {module:model/ComponentsSchemasIntervalFormsItem} The populated <code>ComponentsSchemasIntervalFormsItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComponentsSchemasIntervalFormsItem();

            if (data.hasOwnProperty('formId')) {
                obj['formId'] = ApiClient.convertToType(data['formId'], 'Number');
            }
            if (data.hasOwnProperty('formKey')) {
                obj['formKey'] = ApiClient.convertToType(data['formKey'], 'String');
            }
            if (data.hasOwnProperty('formName')) {
                obj['formName'] = ApiClient.convertToType(data['formName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ComponentsSchemasIntervalFormsItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ComponentsSchemasIntervalFormsItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['formKey'] && !(typeof data['formKey'] === 'string' || data['formKey'] instanceof String)) {
            throw new Error("Expected the field `formKey` to be a primitive type in the JSON string but got " + data['formKey']);
        }
        // ensure the json data is a string
        if (data['formName'] && !(typeof data['formName'] === 'string' || data['formName'] instanceof String)) {
            throw new Error("Expected the field `formName` to be a primitive type in the JSON string but got " + data['formName']);
        }

        return true;
    }


}



/**
 * Form ID scheduled in the interval
 * @member {Number} formId
 */
ComponentsSchemasIntervalFormsItem.prototype['formId'] = undefined;

/**
 * Form key scheduled in the interval
 * @member {String} formKey
 */
ComponentsSchemasIntervalFormsItem.prototype['formKey'] = undefined;

/**
 * Form name scheduled in the interval
 * @member {String} formName
 */
ComponentsSchemasIntervalFormsItem.prototype['formName'] = undefined;






export default ComponentsSchemasIntervalFormsItem;

