/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecordJobStatus model module.
 * @module model/RecordJobStatus
 * @version 1.0.15
 */
class RecordJobStatus {
    /**
     * Constructs a new <code>RecordJobStatus</code>.
     * @alias module:model/RecordJobStatus
     */
    constructor() { 
        
        RecordJobStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecordJobStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecordJobStatus} obj Optional instance to populate.
     * @return {module:model/RecordJobStatus} The populated <code>RecordJobStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordJobStatus();

            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
            }
            if (data.hasOwnProperty('batchId')) {
                obj['batchId'] = ApiClient.convertToType(data['batchId'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecordJobStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecordJobStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['jobId'] && !(typeof data['jobId'] === 'string' || data['jobId'] instanceof String)) {
            throw new Error("Expected the field `jobId` to be a primitive type in the JSON string but got " + data['jobId']);
        }
        // ensure the json data is a string
        if (data['batchId'] && !(typeof data['batchId'] === 'string' || data['batchId'] instanceof String)) {
            throw new Error("Expected the field `batchId` to be a primitive type in the JSON string but got " + data['batchId']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}



/**
 * Unique job identifier
 * @member {String} jobId
 */
RecordJobStatus.prototype['jobId'] = undefined;

/**
 * Batch ID used to track the job (identical to jobId in most cases)
 * @member {String} batchId
 */
RecordJobStatus.prototype['batchId'] = undefined;

/**
 * Current state of the job (e.g., created, completed)
 * @member {String} state
 */
RecordJobStatus.prototype['state'] = undefined;






export default RecordJobStatus;

