/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import Pagination from './Pagination';
import User from './User';

/**
 * The UserList model module.
 * @module model/UserList
 * @version 1.0.15
 */
class UserList {
    /**
     * Constructs a new <code>UserList</code>.
     * @alias module:model/UserList
     */
    constructor() { 
        
        UserList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserList} obj Optional instance to populate.
     * @return {module:model/UserList} The populated <code>UserList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserList();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [User]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserList</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          Metadata.validateJSON(data['metadata']);
        }
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          Pagination.validateJSON(data['pagination']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                User.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/Metadata} metadata
 */
UserList.prototype['metadata'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
UserList.prototype['pagination'] = undefined;

/**
 * @member {Array.<module:model/User>} data
 */
UserList.prototype['data'] = undefined;






export default UserList;

