# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StudiesApi")

api_instance <- StudiesApi$new()

test_that("ListStudies", {
  # tests for ListStudies
  # base path: https://edc.prod.imednetapi.com/api/v1/edc
  # List studies accessible by API key
  # @param page integer Page index to retrieve (0-based) (optional)
  # @param size integer Number of items to return per page (max 500) (optional)
  # @param sort character Sorting criteria in the format `property,ASC` or `property,DESC`. Can be repeated. (optional)
  # @param filter character Optional filter criteria to apply, in the format `attribute==value` with support for >, >=, <, <=, !=. Multiple criteria can be combined with `;` (AND) or `,` (OR). (optional)
  # @return [StudyList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
