# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Sort")

model_instance <- Sort$new()

test_that("property", {
  # tests for the property `property` (character)
  # Name of the property by which the result is sorted

  # uncomment below to test the property
  #expect_equal(model.instance$`property`, "EXPECTED_RESULT")
})

test_that("direction", {
  # tests for the property `direction` (character)
  # Sort direction (ASC or DESC)

  # uncomment below to test the property
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})
