/*
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.Keyword;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Record
 */
public class RecordTest {
    private final Record model = new Record();

    /**
     * Model tests for Record
     */
    @Test
    public void testRecord() {
        // TODO: test Record
    }

    /**
     * Test the property 'studyKey'
     */
    @Test
    public void studyKeyTest() {
        // TODO: test studyKey
    }

    /**
     * Test the property 'intervalId'
     */
    @Test
    public void intervalIdTest() {
        // TODO: test intervalId
    }

    /**
     * Test the property 'formId'
     */
    @Test
    public void formIdTest() {
        // TODO: test formId
    }

    /**
     * Test the property 'formKey'
     */
    @Test
    public void formKeyTest() {
        // TODO: test formKey
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'recordId'
     */
    @Test
    public void recordIdTest() {
        // TODO: test recordId
    }

    /**
     * Test the property 'recordOid'
     */
    @Test
    public void recordOidTest() {
        // TODO: test recordOid
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'recordStatus'
     */
    @Test
    public void recordStatusTest() {
        // TODO: test recordStatus
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

    /**
     * Test the property 'subjectId'
     */
    @Test
    public void subjectIdTest() {
        // TODO: test subjectId
    }

    /**
     * Test the property 'subjectOid'
     */
    @Test
    public void subjectOidTest() {
        // TODO: test subjectOid
    }

    /**
     * Test the property 'subjectKey'
     */
    @Test
    public void subjectKeyTest() {
        // TODO: test subjectKey
    }

    /**
     * Test the property 'visitId'
     */
    @Test
    public void visitIdTest() {
        // TODO: test visitId
    }

    /**
     * Test the property 'parentRecordId'
     */
    @Test
    public void parentRecordIdTest() {
        // TODO: test parentRecordId
    }

    /**
     * Test the property 'keywords'
     */
    @Test
    public void keywordsTest() {
        // TODO: test keywords
    }

    /**
     * Test the property 'recordData'
     */
    @Test
    public void recordDataTest() {
        // TODO: test recordData
    }

}
