/*
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Visit
 */
public class VisitTest {
    private final Visit model = new Visit();

    /**
     * Model tests for Visit
     */
    @Test
    public void testVisit() {
        // TODO: test Visit
    }

    /**
     * Test the property 'studyKey'
     */
    @Test
    public void studyKeyTest() {
        // TODO: test studyKey
    }

    /**
     * Test the property 'visitId'
     */
    @Test
    public void visitIdTest() {
        // TODO: test visitId
    }

    /**
     * Test the property 'intervalId'
     */
    @Test
    public void intervalIdTest() {
        // TODO: test intervalId
    }

    /**
     * Test the property 'intervalName'
     */
    @Test
    public void intervalNameTest() {
        // TODO: test intervalName
    }

    /**
     * Test the property 'subjectId'
     */
    @Test
    public void subjectIdTest() {
        // TODO: test subjectId
    }

    /**
     * Test the property 'subjectKey'
     */
    @Test
    public void subjectKeyTest() {
        // TODO: test subjectKey
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'visitDate'
     */
    @Test
    public void visitDateTest() {
        // TODO: test visitDate
    }

    /**
     * Test the property 'visitDateForm'
     */
    @Test
    public void visitDateFormTest() {
        // TODO: test visitDateForm
    }

    /**
     * Test the property 'visitDateQuestion'
     */
    @Test
    public void visitDateQuestionTest() {
        // TODO: test visitDateQuestion
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

}
