=begin
#Mednet EDC API

#The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 

The version of the OpenAPI document: 1.0.15

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/coding'
require 'openapi_client/models/coding_list'
require 'openapi_client/models/components_schemas_interval_forms_item'
require 'openapi_client/models/components_schemas_metadata_error'
require 'openapi_client/models/components_schemas_record_create_request_item'
require 'openapi_client/models/form'
require 'openapi_client/models/form_list'
require 'openapi_client/models/inline_object'
require 'openapi_client/models/inline_object1'
require 'openapi_client/models/inline_object2'
require 'openapi_client/models/inline_object3'
require 'openapi_client/models/inline_object4'
require 'openapi_client/models/inline_object5'
require 'openapi_client/models/interval'
require 'openapi_client/models/interval_list'
require 'openapi_client/models/job'
require 'openapi_client/models/keyword'
require 'openapi_client/models/metadata'
require 'openapi_client/models/pagination'
require 'openapi_client/models/query'
require 'openapi_client/models/query_comment'
require 'openapi_client/models/query_list'
require 'openapi_client/models/record'
require 'openapi_client/models/record_job_status'
require 'openapi_client/models/record_list'
require 'openapi_client/models/record_revision'
require 'openapi_client/models/record_revision_list'
require 'openapi_client/models/role'
require 'openapi_client/models/site'
require 'openapi_client/models/site_list'
require 'openapi_client/models/sort'
require 'openapi_client/models/study'
require 'openapi_client/models/study_list'
require 'openapi_client/models/subject'
require 'openapi_client/models/subject_list'
require 'openapi_client/models/user'
require 'openapi_client/models/user_list'
require 'openapi_client/models/variable'
require 'openapi_client/models/variable_list'
require 'openapi_client/models/visit'
require 'openapi_client/models/visit_list'

# APIs
require 'openapi_client/api/administration_api'
require 'openapi_client/api/codings_api'
require 'openapi_client/api/forms_api'
require 'openapi_client/api/intervals_api'
require 'openapi_client/api/jobs_api'
require 'openapi_client/api/queries_api'
require 'openapi_client/api/record_revisions_api'
require 'openapi_client/api/records_api'
require 'openapi_client/api/sites_api'
require 'openapi_client/api/studies_api'
require 'openapi_client/api/subjects_api'
require 'openapi_client/api/variables_api'
require 'openapi_client/api/visits_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
