/*
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Study
 */
public class StudyTest {
    private final Study model = new Study();

    /**
     * Model tests for Study
     */
    @Test
    public void testStudy() {
        // TODO: test Study
    }

    /**
     * Test the property 'sponsorKey'
     */
    @Test
    public void sponsorKeyTest() {
        // TODO: test sponsorKey
    }

    /**
     * Test the property 'studyKey'
     */
    @Test
    public void studyKeyTest() {
        // TODO: test studyKey
    }

    /**
     * Test the property 'studyId'
     */
    @Test
    public void studyIdTest() {
        // TODO: test studyId
    }

    /**
     * Test the property 'studyName'
     */
    @Test
    public void studyNameTest() {
        // TODO: test studyName
    }

    /**
     * Test the property 'studyDescription'
     */
    @Test
    public void studyDescriptionTest() {
        // TODO: test studyDescription
    }

    /**
     * Test the property 'studyType'
     */
    @Test
    public void studyTypeTest() {
        // TODO: test studyType
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

}
