/*
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Variable
 */
public class VariableTest {
    private final Variable model = new Variable();

    /**
     * Model tests for Variable
     */
    @Test
    public void testVariable() {
        // TODO: test Variable
    }

    /**
     * Test the property 'studyKey'
     */
    @Test
    public void studyKeyTest() {
        // TODO: test studyKey
    }

    /**
     * Test the property 'variableId'
     */
    @Test
    public void variableIdTest() {
        // TODO: test variableId
    }

    /**
     * Test the property 'variableType'
     */
    @Test
    public void variableTypeTest() {
        // TODO: test variableType
    }

    /**
     * Test the property 'variableName'
     */
    @Test
    public void variableNameTest() {
        // TODO: test variableName
    }

    /**
     * Test the property 'sequence'
     */
    @Test
    public void sequenceTest() {
        // TODO: test sequence
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

    /**
     * Test the property 'formId'
     */
    @Test
    public void formIdTest() {
        // TODO: test formId
    }

    /**
     * Test the property 'variableOid'
     */
    @Test
    public void variableOidTest() {
        // TODO: test variableOid
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'formKey'
     */
    @Test
    public void formKeyTest() {
        // TODO: test formKey
    }

    /**
     * Test the property 'formName'
     */
    @Test
    public void formNameTest() {
        // TODO: test formName
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'blinded'
     */
    @Test
    public void blindedTest() {
        // TODO: test blinded
    }

}
