#' Mednet EDC API
#'
#' The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
#'
#' The version of the OpenAPI document: 1.0.15
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Intervals operations
#' @description IntervalsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ListIntervals  ####################
#'
#' library(openapi)
#' var_study_key <- "study_key_example" # character | Study key identifying the study context for the request
#' var_page <- 0 # integer | Page index to retrieve (0-based) (Optional)
#' var_size <- 25 # integer | Number of items to return per page (max 500) (Optional)
#' var_sort <- "sort_example" # character | Sorting criteria in the format `property,ASC` or `property,DESC`. Can be repeated. (Optional)
#' var_filter <- "filter_example" # character | Optional filter criteria to apply, in the format `attribute==value` with support for >, >=, <, <=, !=. Multiple criteria can be combined with `;` (AND) or `,` (OR). (Optional)
#'
#' #List intervals (visit definitions) in a study
#' api_instance <- IntervalsApi$new()
#'
#' # Configure API key authorization: apiKeyAuth
#' api_instance$api_client$api_keys["x-api-key"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: securityKeyAuth
#' api_instance$api_client$api_keys["x-imn-security-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListIntervals(var_study_key, page = var_page, size = var_size, sort = var_sort, filter = var_filterdata_file = "result.txt")
#' result <- api_instance$ListIntervals(var_study_key, page = var_page, size = var_size, sort = var_sort, filter = var_filter)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
IntervalsApi <- R6::R6Class(
  "IntervalsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new IntervalsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' List intervals (visit definitions) in a study
    #'
    #' @param study_key Study key identifying the study context for the request
    #' @param page (optional) Page index to retrieve (0-based) (default value: 0)
    #' @param size (optional) Number of items to return per page (max 500) (default value: 25)
    #' @param sort (optional) Sorting criteria in the format `property,ASC` or `property,DESC`. Can be repeated.
    #' @param filter (optional) Optional filter criteria to apply, in the format `attribute==value` with support for >, >=, <, <=, !=. Multiple criteria can be combined with `;` (AND) or `,` (OR).
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return IntervalList
    ListIntervals = function(study_key, page = 0, size = 25, sort = NULL, filter = NULL, data_file = NULL, ...) {
      local_var_response <- self$ListIntervalsWithHttpInfo(study_key, page, size, sort, filter, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List intervals (visit definitions) in a study
    #'
    #' @param study_key Study key identifying the study context for the request
    #' @param page (optional) Page index to retrieve (0-based) (default value: 0)
    #' @param size (optional) Number of items to return per page (max 500) (default value: 25)
    #' @param sort (optional) Sorting criteria in the format `property,ASC` or `property,DESC`. Can be repeated.
    #' @param filter (optional) Optional filter criteria to apply, in the format `attribute==value` with support for >, >=, <, <=, !=. Multiple criteria can be combined with `;` (AND) or `,` (OR).
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (IntervalList) with additional information such as HTTP status code, headers
    ListIntervalsWithHttpInfo = function(study_key, page = 0, size = 25, sort = NULL, filter = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`study_key`)) {
        stop("Missing required parameter `study_key`.")
      }


      if (`page` < 0) {
        stop("Invalid value for `page` when calling IntervalsApi$ListIntervals, must be bigger than or equal to 0.")
      }

      if (`size` > 500) {
        stop("Invalid value for `size` when calling IntervalsApi$ListIntervals, must be smaller than or equal to 500.")
      }
      if (`size` < 1) {
        stop("Invalid value for `size` when calling IntervalsApi$ListIntervals, must be bigger than or equal to 1.")
      }



      query_params[["page"]] <- `page`

      query_params[["size"]] <- `size`

      query_params[["sort"]] <- `sort`

      query_params[["filter"]] <- `filter`

      local_var_url_path <- "/studies/{studyKey}/intervals"
      if (!missing(`study_key`)) {
        local_var_url_path <- gsub("\\{studyKey\\}", URLencode(as.character(`study_key`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("x-api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["x-api-key"]) > 0) {
        header_params["x-api-key"] <- paste(unlist(self$api_client$api_keys["x-api-key"]), collapse = "")
      }
      # API key authentication
      if ("x-imn-security-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["x-imn-security-key"]) > 0) {
        header_params["x-imn-security-key"] <- paste(unlist(self$api_client$api_keys["x-imn-security-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "IntervalList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
