/**
 * Mednet EDC API
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MednetEdcApi);
  }
}(this, function(expect, MednetEdcApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MednetEdcApi.Form();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Form', function() {
    it('should create an instance of Form', function() {
      // uncomment below and update the code to test Form
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be.a(MednetEdcApi.Form);
    });

    it('should have the property studyKey (base name: "studyKey")', function() {
      // uncomment below and update the code to test the property studyKey
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property formId (base name: "formId")', function() {
      // uncomment below and update the code to test the property formId
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property formKey (base name: "formKey")', function() {
      // uncomment below and update the code to test the property formKey
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property formName (base name: "formName")', function() {
      // uncomment below and update the code to test the property formName
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property formType (base name: "formType")', function() {
      // uncomment below and update the code to test the property formType
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property revision (base name: "revision")', function() {
      // uncomment below and update the code to test the property revision
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property embeddedLog (base name: "embeddedLog")', function() {
      // uncomment below and update the code to test the property embeddedLog
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property enforceOwnership (base name: "enforceOwnership")', function() {
      // uncomment below and update the code to test the property enforceOwnership
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property userAgreement (base name: "userAgreement")', function() {
      // uncomment below and update the code to test the property userAgreement
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property subjectRecordReport (base name: "subjectRecordReport")', function() {
      // uncomment below and update the code to test the property subjectRecordReport
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property unscheduledVisit (base name: "unscheduledVisit")', function() {
      // uncomment below and update the code to test the property unscheduledVisit
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property otherForms (base name: "otherForms")', function() {
      // uncomment below and update the code to test the property otherForms
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property eproForm (base name: "eproForm")', function() {
      // uncomment below and update the code to test the property eproForm
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property allowCopy (base name: "allowCopy")', function() {
      // uncomment below and update the code to test the property allowCopy
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property disabled (base name: "disabled")', function() {
      // uncomment below and update the code to test the property disabled
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

    it('should have the property dateModified (base name: "dateModified")', function() {
      // uncomment below and update the code to test the property dateModified
      //var instance = new MednetEdcApi.Form();
      //expect(instance).to.be();
    });

  });

}));
