/*
 * Mednet EDC API
 *
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Coding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Coding
        //private Coding instance;

        public CodingTests()
        {
            // TODO uncomment below to create an instance of Coding
            //instance = new Coding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Coding
        /// </summary>
        [Fact]
        public void CodingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Coding
            //Assert.IsType<Coding>(instance);
        }

        /// <summary>
        /// Test the property 'StudyKey'
        /// </summary>
        [Fact]
        public void StudyKeyTest()
        {
            // TODO unit test for the property 'StudyKey'
        }

        /// <summary>
        /// Test the property 'SiteName'
        /// </summary>
        [Fact]
        public void SiteNameTest()
        {
            // TODO unit test for the property 'SiteName'
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }

        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }

        /// <summary>
        /// Test the property 'SubjectKey'
        /// </summary>
        [Fact]
        public void SubjectKeyTest()
        {
            // TODO unit test for the property 'SubjectKey'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'FormName'
        /// </summary>
        [Fact]
        public void FormNameTest()
        {
            // TODO unit test for the property 'FormName'
        }

        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Fact]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }

        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Fact]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

        /// <summary>
        /// Test the property 'RecordId'
        /// </summary>
        [Fact]
        public void RecordIdTest()
        {
            // TODO unit test for the property 'RecordId'
        }

        /// <summary>
        /// Test the property 'Variable'
        /// </summary>
        [Fact]
        public void VariableTest()
        {
            // TODO unit test for the property 'Variable'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'CodingId'
        /// </summary>
        [Fact]
        public void CodingIdTest()
        {
            // TODO unit test for the property 'CodingId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'CodedBy'
        /// </summary>
        [Fact]
        public void CodedByTest()
        {
            // TODO unit test for the property 'CodedBy'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'DictionaryName'
        /// </summary>
        [Fact]
        public void DictionaryNameTest()
        {
            // TODO unit test for the property 'DictionaryName'
        }

        /// <summary>
        /// Test the property 'DictionaryVersion'
        /// </summary>
        [Fact]
        public void DictionaryVersionTest()
        {
            // TODO unit test for the property 'DictionaryVersion'
        }

        /// <summary>
        /// Test the property 'DateCoded'
        /// </summary>
        [Fact]
        public void DateCodedTest()
        {
            // TODO unit test for the property 'DateCoded'
        }
    }
}
