/*
 * Mednet EDC API
 *
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RecordRevision
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecordRevisionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecordRevision
        //private RecordRevision instance;

        public RecordRevisionTests()
        {
            // TODO uncomment below to create an instance of RecordRevision
            //instance = new RecordRevision();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecordRevision
        /// </summary>
        [Fact]
        public void RecordRevisionInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecordRevision
            //Assert.IsType<RecordRevision>(instance);
        }

        /// <summary>
        /// Test the property 'StudyKey'
        /// </summary>
        [Fact]
        public void StudyKeyTest()
        {
            // TODO unit test for the property 'StudyKey'
        }

        /// <summary>
        /// Test the property 'RecordRevisionId'
        /// </summary>
        [Fact]
        public void RecordRevisionIdTest()
        {
            // TODO unit test for the property 'RecordRevisionId'
        }

        /// <summary>
        /// Test the property 'RecordId'
        /// </summary>
        [Fact]
        public void RecordIdTest()
        {
            // TODO unit test for the property 'RecordId'
        }

        /// <summary>
        /// Test the property 'RecordOid'
        /// </summary>
        [Fact]
        public void RecordOidTest()
        {
            // TODO unit test for the property 'RecordOid'
        }

        /// <summary>
        /// Test the property 'VarRecordRevision'
        /// </summary>
        [Fact]
        public void VarRecordRevisionTest()
        {
            // TODO unit test for the property 'VarRecordRevision'
        }

        /// <summary>
        /// Test the property 'DataRevision'
        /// </summary>
        [Fact]
        public void DataRevisionTest()
        {
            // TODO unit test for the property 'DataRevision'
        }

        /// <summary>
        /// Test the property 'RecordStatus'
        /// </summary>
        [Fact]
        public void RecordStatusTest()
        {
            // TODO unit test for the property 'RecordStatus'
        }

        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }

        /// <summary>
        /// Test the property 'SubjectOid'
        /// </summary>
        [Fact]
        public void SubjectOidTest()
        {
            // TODO unit test for the property 'SubjectOid'
        }

        /// <summary>
        /// Test the property 'SubjectKey'
        /// </summary>
        [Fact]
        public void SubjectKeyTest()
        {
            // TODO unit test for the property 'SubjectKey'
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }

        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Fact]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }

        /// <summary>
        /// Test the property 'IntervalId'
        /// </summary>
        [Fact]
        public void IntervalIdTest()
        {
            // TODO unit test for the property 'IntervalId'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'ReasonForChange'
        /// </summary>
        [Fact]
        public void ReasonForChangeTest()
        {
            // TODO unit test for the property 'ReasonForChange'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
    }
}
