/*
 * Mednet EDC API
 *
 * The Mednet EDC (Electronic Data Capture) REST API provides a single-point of access for reading data stored across iMednet data services. This specification documents all available endpoints in the latest version of the API. 
 *
 * The version of the OpenAPI document: 1.0.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Record
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Record
        //private Record instance;

        public RecordTests()
        {
            // TODO uncomment below to create an instance of Record
            //instance = new Record();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Record
        /// </summary>
        [Fact]
        public void RecordInstanceTest()
        {
            // TODO uncomment below to test "IsType" Record
            //Assert.IsType<Record>(instance);
        }

        /// <summary>
        /// Test the property 'StudyKey'
        /// </summary>
        [Fact]
        public void StudyKeyTest()
        {
            // TODO unit test for the property 'StudyKey'
        }

        /// <summary>
        /// Test the property 'IntervalId'
        /// </summary>
        [Fact]
        public void IntervalIdTest()
        {
            // TODO unit test for the property 'IntervalId'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'FormKey'
        /// </summary>
        [Fact]
        public void FormKeyTest()
        {
            // TODO unit test for the property 'FormKey'
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }

        /// <summary>
        /// Test the property 'RecordId'
        /// </summary>
        [Fact]
        public void RecordIdTest()
        {
            // TODO unit test for the property 'RecordId'
        }

        /// <summary>
        /// Test the property 'RecordOid'
        /// </summary>
        [Fact]
        public void RecordOidTest()
        {
            // TODO unit test for the property 'RecordOid'
        }

        /// <summary>
        /// Test the property 'RecordType'
        /// </summary>
        [Fact]
        public void RecordTypeTest()
        {
            // TODO unit test for the property 'RecordType'
        }

        /// <summary>
        /// Test the property 'RecordStatus'
        /// </summary>
        [Fact]
        public void RecordStatusTest()
        {
            // TODO unit test for the property 'RecordStatus'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }

        /// <summary>
        /// Test the property 'DateModified'
        /// </summary>
        [Fact]
        public void DateModifiedTest()
        {
            // TODO unit test for the property 'DateModified'
        }

        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }

        /// <summary>
        /// Test the property 'SubjectOid'
        /// </summary>
        [Fact]
        public void SubjectOidTest()
        {
            // TODO unit test for the property 'SubjectOid'
        }

        /// <summary>
        /// Test the property 'SubjectKey'
        /// </summary>
        [Fact]
        public void SubjectKeyTest()
        {
            // TODO unit test for the property 'SubjectKey'
        }

        /// <summary>
        /// Test the property 'VisitId'
        /// </summary>
        [Fact]
        public void VisitIdTest()
        {
            // TODO unit test for the property 'VisitId'
        }

        /// <summary>
        /// Test the property 'ParentRecordId'
        /// </summary>
        [Fact]
        public void ParentRecordIdTest()
        {
            // TODO unit test for the property 'ParentRecordId'
        }

        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Fact]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }

        /// <summary>
        /// Test the property 'RecordData'
        /// </summary>
        [Fact]
        public void RecordDataTest()
        {
            // TODO unit test for the property 'RecordData'
        }
    }
}
